// Ponte segura entre a UI (renderer) e o processo principal.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  wipeLocalData: () => ipcRenderer.invoke("wipe-local-data"),
  getOnboarding: () => ipcRenderer.invoke("get-onboarding"),
  completeOnboarding: (payload) => ipcRenderer.invoke("complete-onboarding", payload),
  getLibraryDir: () => ipcRenderer.invoke("get-library-dir"),
  pickLibraryDir: () => ipcRenderer.invoke("pick-library-dir"),
  setLibraryDir: (dir) => ipcRenderer.invoke("set-library-dir", dir),
  pickFile: () => ipcRenderer.invoke("pick-file"),
  getProvider: () => ipcRenderer.invoke("get-provider"),
  setProvider: (p) => ipcRenderer.invoke("set-provider", p),
  getConnectedProviders: () => ipcRenderer.invoke("get-connected-providers"),
  getKey: (provider) => ipcRenderer.invoke("get-key", provider),
  setKey: (provider, k) => ipcRenderer.invoke("set-key", provider, k),
  openFolder: (p) => ipcRenderer.invoke("open-folder", p),
  getLinkPreview: (url) => ipcRenderer.invoke("get-link-preview", url),
  validateKey: (provider, k) => ipcRenderer.invoke("validate-key", provider, k),
  getStats: () => ipcRenderer.invoke("get-stats"),
  listClips: () => ipcRenderer.invoke("list-clips"),
  generate: (opts) => ipcRenderer.send("generate", opts),
  onProgress: (cb) => ipcRenderer.on("job-progress", (_e, m) => cb(m)),
  onDone: (cb) => ipcRenderer.on("job-done", (_e, m) => cb(m)),
  onWarning: (cb) => ipcRenderer.on("job-warning", (_e, m) => cb(m)),
  onError: (cb) => ipcRenderer.on("job-error", (_e, m) => cb(m)),
  // Versao + auto-update
  getVersion: () => ipcRenderer.invoke("get-version"),
  openDownloadPage: () => ipcRenderer.invoke("open-download-page"),
  openGithub: () => ipcRenderer.invoke("open-github"),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  copyText: (text) => ipcRenderer.invoke("copy-text", text),
  downloadUpdate: () => ipcRenderer.invoke("update-download"),
  installUpdate: () => ipcRenderer.invoke("update-install"),
  downloadMacUpdate: () => ipcRenderer.invoke("download-mac-update"),
  onUpdateAvailable: (cb) => ipcRenderer.on("update-available", (_e, m) => cb(m)),
  onUpdateProgress: (cb) => ipcRenderer.on("update-progress", (_e, m) => cb(m)),
  onUpdateReady: (cb) => ipcRenderer.on("update-ready", (_e, m) => cb(m)),
  onUpdateSite: (cb) => ipcRenderer.on("update-site", (_e, m) => cb(m)),
  onMacUpdateOpened: (cb) => ipcRenderer.on("mac-update-opened", (_e, m) => cb(m)),
  onMacUpdateError: (cb) => ipcRenderer.on("mac-update-error", (_e, m) => cb(m)),
});
