// Ponte segura entre a UI (renderer) e o processo principal.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  signIn: (email, password) => ipcRenderer.invoke("auth-sign-in", { email, password }),
  signUp: (email, password) => ipcRenderer.invoke("auth-sign-up", { email, password }),
  signOut: () => ipcRenderer.invoke("auth-sign-out"),
  getSession: () => ipcRenderer.invoke("auth-get-session"),
  getAccount: () => ipcRenderer.invoke("get-account"),
  recoverPassword: (email) => ipcRenderer.invoke("auth-recover", { email }),
  wipeLocalData: () => ipcRenderer.invoke("wipe-local-data"),
  deleteAccount: () => ipcRenderer.invoke("auth-delete-account"),
  getOnboarding: () => ipcRenderer.invoke("get-onboarding"),
  completeOnboarding: (payload) => ipcRenderer.invoke("complete-onboarding", payload),
  getLibraryDir: () => ipcRenderer.invoke("get-library-dir"),
  pickLibraryDir: () => ipcRenderer.invoke("pick-library-dir"),
  setLibraryDir: (dir) => ipcRenderer.invoke("set-library-dir", dir),
  pickFile: () => ipcRenderer.invoke("pick-file"),
  getKey: () => ipcRenderer.invoke("get-key"),
  setKey: (k) => ipcRenderer.invoke("set-key", k),
  openFolder: (p) => ipcRenderer.invoke("open-folder", p),
  getLinkPreview: (url) => ipcRenderer.invoke("get-link-preview", url),
  validateKey: (k) => ipcRenderer.invoke("validate-key", k),
  getStats: () => ipcRenderer.invoke("get-stats"),
  listClips: () => ipcRenderer.invoke("list-clips"),
  generate: (opts) => ipcRenderer.send("generate", opts),
  onProgress: (cb) => ipcRenderer.on("job-progress", (_e, m) => cb(m)),
  onDone: (cb) => ipcRenderer.on("job-done", (_e, m) => cb(m)),
  onWarning: (cb) => ipcRenderer.on("job-warning", (_e, m) => cb(m)),
  onError: (cb) => ipcRenderer.on("job-error", (_e, m) => cb(m)),
});
